### ISSUE TITLE
ClipBoard History Issue

### ISSUE THREAD

**Issue by ctf0** [eecolella/emmet-style-reflector#1]
this plugin is a true time saver ,the issue i have is when i write anything with emmet then go copy some text from somewhere else to paste it (paragraph ,etc..) ,the plugin ignore that and only remember the emmet selector that will go into the CSS file ,is it possible to change that behavior ?

**Comment by btm1** [comment]
OMG i thought this was a core issue with sublime and realized today that it was this plugin. The most annoying thing ever.... If there was a way to fix it I would go back to using this.

**Comment by JulienMelissas** [comment]
Hey I think this is happening to me too!

**Comment by r3nandotdev** [comment]
It happens to me too since long ago and never found out the solution :|

**Comment by d0mlthebread** [comment]
anyone has a solution to that?! it is really annoying!

**Comment by trouba** [comment]
Same here, disabled the package until there is a fix

**Comment by igorbarbashin** [comment]
I don't think this plugin gives enough value to tolerate this bug. I think I installed this plugin by mistake (thinking it's actual Emmet). I'd recommend not to use this plugin, it wasn't supported for 2 years
